# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import try_protos_pb2 as try__protos__pb2


class SensorsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RelayState = channel.unary_unary(
                '/grpc_try.Sensors/RelayState',
                request_serializer=try__protos__pb2.RelayRequest.SerializeToString,
                response_deserializer=try__protos__pb2.RelayResponse.FromString,
                )


class SensorsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RelayState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RelayState': grpc.unary_unary_rpc_method_handler(
                    servicer.RelayState,
                    request_deserializer=try__protos__pb2.RelayRequest.FromString,
                    response_serializer=try__protos__pb2.RelayResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_try.Sensors', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sensors(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RelayState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_try.Sensors/RelayState',
            try__protos__pb2.RelayRequest.SerializeToString,
            try__protos__pb2.RelayResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
