# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: try_protos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10try_protos.proto\x12\x08grpc_try\"=\n\x0cRelayRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\x10\n\x08position\x18\x03 \x01(\r\",\n\rRelayResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\r2J\n\x07Sensors\x12?\n\nRelayState\x12\x16.grpc_try.RelayRequest\x1a\x17.grpc_try.RelayResponse\"\x00\x42#\n\x0fio.grpc.grpctryB\x08TryProtoP\x01\xa2\x02\x03TRYb\x06proto3')



_RELAYREQUEST = DESCRIPTOR.message_types_by_name['RelayRequest']
_RELAYRESPONSE = DESCRIPTOR.message_types_by_name['RelayResponse']
RelayRequest = _reflection.GeneratedProtocolMessageType('RelayRequest', (_message.Message,), {
  'DESCRIPTOR' : _RELAYREQUEST,
  '__module__' : 'try_protos_pb2'
  # @@protoc_insertion_point(class_scope:grpc_try.RelayRequest)
  })
_sym_db.RegisterMessage(RelayRequest)

RelayResponse = _reflection.GeneratedProtocolMessageType('RelayResponse', (_message.Message,), {
  'DESCRIPTOR' : _RELAYRESPONSE,
  '__module__' : 'try_protos_pb2'
  # @@protoc_insertion_point(class_scope:grpc_try.RelayResponse)
  })
_sym_db.RegisterMessage(RelayResponse)

_SENSORS = DESCRIPTOR.services_by_name['Sensors']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017io.grpc.grpctryB\010TryProtoP\001\242\002\003TRY'
  _RELAYREQUEST._serialized_start=30
  _RELAYREQUEST._serialized_end=91
  _RELAYRESPONSE._serialized_start=93
  _RELAYRESPONSE._serialized_end=137
  _SENSORS._serialized_start=139
  _SENSORS._serialized_end=213
# @@protoc_insertion_point(module_scope)
